# Generated by Django 2.2 on 2025-12-23 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='avatars/thumbnails/', verbose_name='头像缩略图')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='个人简介')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='位置')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户简介',
                'verbose_name_plural': '用户简介',
            },
        ),
    ]
