# Generated by Django 3.2.25 on 2025-12-23 02:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='任务名称', max_length=200, unique=True)),
                ('task_function', models.CharField(help_text='任务函数路径', max_length=500)),
                ('schedule', models.CharField(help_text='执行计划，如：每小时、每天等', max_length=200)),
                ('enabled', models.BooleanField(default=True, help_text='是否启用')),
                ('last_run', models.DateTimeField(blank=True, help_text='最后执行时间', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Scheduled Task',
                'verbose_name_plural': 'Scheduled Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(help_text='Celery任务ID', max_length=255, unique=True)),
                ('task_name', models.CharField(help_text='任务名称', max_length=255)),
                ('status', models.CharField(default='PENDING', help_text='任务状态', max_length=50)),
                ('result', models.TextField(blank=True, help_text='任务结果', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Task Record',
                'verbose_name_plural': 'Task Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
