# Generated by Django 2.2 on 2025-12-23 03:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mytask', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduledTask',
        ),
        migrations.AlterModelOptions(
            name='taskrecord',
            options={'ordering': ['-created_at'], 'verbose_name': '任务记录', 'verbose_name_plural': '任务记录'},
        ),
        migrations.AddField(
            model_name='taskrecord',
            name='args',
            field=models.TextField(blank=True, null=True, verbose_name='任务参数'),
        ),
        migrations.AddField(
            model_name='taskrecord',
            name='kwargs',
            field=models.TextField(blank=True, null=True, verbose_name='任务关键字参数'),
        ),
        migrations.AddField(
            model_name='taskrecord',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AddField(
            model_name='taskrecord',
            name='traceback',
            field=models.TextField(blank=True, null=True, verbose_name='错误追踪信息'),
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='result',
            field=models.TextField(blank=True, null=True, verbose_name='任务结果'),
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='status',
            field=models.CharField(default='PENDING', max_length=50, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='task_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='任务ID'),
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='task_name',
            field=models.CharField(max_length=255, verbose_name='任务名称'),
        ),
    ]
