"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--kbxk3o)4v+yk()%b&p7wgx^+h0ik=)iycken3gpc+x)13er7j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 允许任何域名访问
ALLOWED_HOSTS = ['*']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',  # 添加REST框架
    'users',  # 添加用户应用
    'mytask',  # 添加任务记录应用
    'common_app',  # 添加通用应用
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'myproject.middleware.GlobalExceptionMiddleware',  # 添加全局异常处理中间件
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('MYSQL_DATABASE', 'myapp_db'),
        'USER': os.getenv('MYSQL_USER', 'myapp_user'),
        'PASSWORD': os.getenv('MYSQL_PASSWORD', 'myapp_password'),
        'HOST': os.getenv('MYSQL_HOST', 'mysql'),
        'PORT': os.getenv('MYSQL_PORT', '3306'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Media files (User uploads)
MEDIA_URL = '/media/'  # 通过Django视图处理的媒体文件路径

# RustFS/S3 storage configuration for avatars
RUSTFS_ACCESS_KEY = os.getenv('RUSTFS_ACCESS_KEY', 'rustfsadmin')
RUSTFS_SECRET_KEY = os.getenv('RUSTFS_SECRET_KEY', 'rustfsadmin123')
RUSTFS_ENDPOINT_URL = os.getenv('RUSTFS_ENDPOINT_URL', 'http://rustfs:9000')
RUSTFS_BUCKET_NAME = os.getenv('RUSTFS_BUCKET_NAME', 'user-avatars')
RUSTFS_REGION_NAME = os.getenv('RUSTFS_REGION_NAME', 'us-east-1')

# Use RustFS for media files (avatars and thumbnails)
DEFAULT_FILE_STORAGE = 'users.storage.RustFSStorage'

# OpenTelemetry Configuration
OTEL_SERVICE_NAME = os.getenv('OTEL_SERVICE_NAME', 'my-opentelemetry-service')
OTEL_EXPORTER_OTLP_ENDPOINT = os.getenv('OTEL_EXPORTER_OTLP_ENDPOINT', 'http://localhost:4317')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 在文件末尾添加DRF配置
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
}

# CORS配置
CORS_ALLOW_ALL_ORIGINS = True  # 在生产环境中应该限制为特定域名

CORS_ALLOWED_ORIGINS = [
    "http://localhost",
    "http://localhost:80",  # Nginx代理
    "http://127.0.0.1:80",
    "http://localhost:8000",  # 后端开发服务器
    "http://127.0.0.1:8000",
    "http://localhost:8080",  # 前端开发服务器
    "http://127.0.0.1:8080",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# AWS S3 settings for RustFS
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None  # 不设置ACL，使用默认设置
AWS_S3_VERIFY = False  # 不验证SSL证书
AWS_S3_SIGNATURE_VERSION = 's3v4'  # 使用v4签名
AWS_S3_ADDRESSING_STYLE = 'path'  # 使用路径风格访问